# Generated by Django 4.2.27 on 2026-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('download_datetime', models.DateTimeField()),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume download',
                'verbose_name_plural': 'Resume downloads',
                'ordering': ('-download_datetime',),
            },
        ),
    ]
